### ISSUE TITLE
How to Improve?

### ISSUE THREAD

**Issue by RajashekarY** [danielgordon10/re3-tensorflow#3]
Hey Thanks @danielgordon10 for open sourcing the code I want to improve this algorithm in certain conditions, can you tell me some suggestions in scenarios like occlusion, and some times object is being released and catching other objects and gradually increasing the size of ROI, can you suggest me how to solves these issues.

Thanks,
Raja Shekar

**Comment by danielgordon10** [comment]
Improving the tracker is a hard research problem. This was the best version I was able to make.. If you can make it better, feel free, but I won't be of much help.
