### ISSUE TITLE
Object detection

### ISSUE THREAD

**Issue by linuxianLoord** [danielgordon10/re3-tensorflow#4]
Hello Daniel,
Thanks a lot for sharing the code, it's an impressive work.
Now, I'm wondering if this network can be used for video object detection purpose (In my case, traffic video objectdetection)? 
Ideally, the prediction output will be a file with bounding box coordinates and the object class.

**Comment by danielgordon10** [comment]
This project is for object tracking, not detection. It would not be a good choice for a detection system.
